from tkinter import*
root = Tk()
root.title('login app')
root.geometry()
frame = Frame(master=root, height=200, width=360, bg="#d0efff")
lbl1 = Label(frame, text= "Full name",bg ="#3895D3",fg='white',width=12)
lbl2 = Label(frame, text ="email id", bg="#3895D3",fg='white',width=12)
lbl3 = Label(frame, text ="enter password", bg="#3895D3",fg='white',width=12)
nameentry = Entry(frame)
emailentry = Entry(frame)
passentry = Entry(frame, show="*")
def display():
    name = name.entry.get()
    greet = "Hey"+name
    message = "/nCongratulations for your new account"
    textbox.insert(END, greet)
    textbox.insert(END, message)
textbox = Text(bg="#BEBEBE", fg = "black")
btn = Button(text = "create account", command=display,bg="red")
frame.place(x=20,y=0)
lbl1.place(x=20,y=0) 
nameentry.place(x=150, y=20)
lbl2.place(x=20, y=80)
emailentry.place(x=150, y=80) 
lbl3.place(x=150, y=80) 
passentry.place(x=150, y=140)
btn.place(x=130, y = 210)
textbox.place(y=250)
root.mainloop() 
